### ISSUE TITLE
4 lint errors in fileA.js

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-ruchikatokish/Webpack#1]
2:1   error  Expected indentation of 4 spaces but found 1 tab  indent
  2:26  error  Strings must use singlequote                      quotes
  2:44  error  Strings must use singlequote                      quotes
  2:66  error  Extra semicolon                                   semi

**Comment by techsquad-ruchikatokish** [comment]
Added custom .eslintrc.js file for js file validation.
